on:
  push:
    branches:
      - main
  pull_request:
name: dprint check
jobs:
  check-style:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check with dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh -s 0.45.0 > /dev/null 2>&1
          $HOME/.dprint/bin/dprint check --allow-no-files
  fix-style:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check with dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh -s 0.45.0 > /dev/null 2>&1
          $HOME/.dprint/bin/dprint fmt --allow-no-files
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply dpring format changes

